services:
  #servicio catalogo
  catalog-service:
    build:
      context: ./services/catalog-service 
      dockerfile: Dockerfile
    container_name: catalog-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://ctgadmin:123456@db-catalog:5432/catalog_db"
      PORT: 3000
    depends_on:
      db-catalog:
        condition: service_healthy

  #servicio inventory
  inventory-service:
    build:
      context: ./services/inventory-service 
      dockerfile: Dockerfile
    container_name: inventory-app
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://invadmin:123456@db-inventory:5432/inventory_db"
      PORT: 3000
    depends_on:
      db-inventory:
        condition: service_healthy

  # Base de datos para el servicio de Catálogo
  db-catalog:
    image: postgres:17-alpine
    container_name: catalog-db
    environment:
      POSTGRES_USER: ctgadmin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctgadmin -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Base de datos para el servicio de Inventario
  db-inventory:
    image: postgres:17-alpine
    container_name: inventory-db
    environment:
      POSTGRES_USER: invadmin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invadmin -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  catalog_data:
  inventory_data: